contour:
  configInline:
    gateway:
      gatewayRef:
        name: contour-gateway
        namespace: projectcontour
  envoy:
    service:
      type: NodePort
      nodePorts:
        http: 31080
        https: 31443