headlamp:
  service:
    type: NodePort
    port: 80
    nodePort: 32080

  ingress:
    enabled: false

  # cluster-admin 생성 방지
  clusterRoleBinding:
    create: false

  # 최소 권한 sa 매핑
  serviceAccount:
    create: false
    name: headlamp-viewer