headlamp:
  serviceAccount:
    create: false
    name: headlamp-viewer

  service:
    type: NodePort
    port: 80
    nodePort: 32080

  ingress:
    enabled: false

  clusterRoleBinding:
    create: false