image:
  tag: "prod-v0.03"
service:
  type: ClusterIP
  port: 8083
httpRoute:
  enabled: true
  hostnames:
    - "admin.doriball.com"
  parentRefs:
    - name: contour-gateway
      namespace: projectcontour
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters: []
springProfile: prod
mongodb:
  secretName: mongodb-secret
  uri: "mongodb-external-service.default.svc.cluster.local"
  port: 2717
  dbName: "calendar_prod"
admin:
  secretName: admin-secret
