image:
  tag: "prod-v0.06"
springProfile: prod
mongodb:
  secretName: mongodb-secret
  uri: "mongodb-external-service.default.svc.cluster.local"
  port: 2717
  dbName: "calendar_prod"
redis:
  secretName: redis-secret
  host: "redis-external-service.default.svc.cluster.local"
  port: 6262
  db: 1
slack:
  secretName: slack-secret
doriball:
  management:
    windowDays: 14
    chunkSize: 100
