image:
  tag: "prod-v0.05"
service:
  type: ClusterIP
  port: 8082
httpRoute:
  enabled: true
  hostnames:
    - "api.doriball.com"
  parentRefs:
    - name: contour-gateway
      namespace: projectcontour
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Forwarded-Proto
                value: https
springProfile: prod
mongodb:
  secretName: mongodb-secret
  uri: "mongodb-external-service.default.svc.cluster.local"
  port: 2717
  dbName: "calendar_prod"
