image:
  tag: "dev-0.2"

service:
  type: NodePort
  port: 8083
  nodePort: 30083

mongodb:
  secretName: mongodb-secret
  uri: "mongodb-external-service.default.svc.cluster.local"
  port: 2717
  dbName: "calendar_dev"

admin:
  secretName: admin-secret