service:
  type: NodePort
  port: 8083
  nodePort: 30083

mongodb:
  secretName: mongodb-secret
  uri: "mongodb-external-service"
  port: 2717
  dbName: "calendar_dev"

admin:
  secretName: admin-secret