image:
  tag: "dev-0.18"
service:
  type: NodePort
  port: 8083
  nodePort: 30083
springProfile: dev
mongodb:
  secretName: mongodb-secret
  uri: "mongodb-external-service.default.svc.cluster.local"
  port: 2717
  dbName: "calendar_dev"
redis:
  secretName: redis-secret
  host: "redis-external-service.default.svc.cluster.local"
  port: 6262
  db: 0
admin:
  secretName: admin-secret
