image:
  tag: "dev-0.09"
springProfile: dev
mongodb:
  secretName: mongodb-secret
  uri: "mongodb-external-service.default.svc.cluster.local"
  port: 2717
  dbName: "calendar_dev"
doriball:
  management:
    windowDays: 14
    chunkSize: 100
