image:
  tag: "dev-0.16"
service:
  type: NodePort
  port: 8082
  nodePort: 30082
springProfile: dev
mongodb:
  secretName: mongodb-secret
  uri: "mongodb-external-service.default.svc.cluster.local"
  port: 2717
  dbName: "calendar_dev"
