configs:
  cm:
    timeout.reconciliation: 600s

argo-cd:
  server:
    service:
      type: NodePort

    extraArgs:
      - --insecure

repoServer:
  replicaCount:
  extraArgs:
    - --git-timeout=30
controller:
  extraArgs:
    - --operation-processors=1
    - --app-operations-processors=1