argo-cd:
  configs:
    cm:
      timeout.reconciliation: 600s
    params:
      reposerver.git.request.timeout: 30s
      reposerver.parallelism.limit: 1

  server:
    service:
      type: NodePort

    extraArgs:
      - --insecure

  repoServer:
    replicaCount:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    livenessProbe:
      timeoutSeconds: 15
      periodSeconds: 60
      failureThreshold: 6
  controller:
    extraArgs:
      - --operation-processors=1
      - --app-operations-processors=1