configs:
  cm:
    timeout.reconciliation: 600s

argo-cd:
  server:
    service:
      type: NodePort

    extraArgs:
      - --insecure

repoServer:
  replicaCount:
  extraArgs:
    - --git-timeout=30
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
controller:
  extraArgs:
    - --operation-processors=1
    - --app-operations-processors=1